server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

  # --- ส่งอีเมลจริงด้วย SMTP (โปรดตั้ง ENV เหล่านี้ใน prod) ---
  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

app:
  mail:
    from: ${MAIL_FROM:noreply@yourdomain.com}
  jwt:
    access-secret: ${JWT_ACCESS_SECRET:DEMO_ACCESS_SECRET_MIN_32_BYTES________________________________}
    refresh-secret: ${JWT_REFRESH_SECRET:DEMO_REFRESH_SECRET_MIN_32_BYTES_______________________________}
    access-expiration-ms: ${JWT_ACCESS_EXPIRE_MS:900000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRE_MS:604800000}
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
      allowed-methods: ${ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
      allowed-headers: ${ALLOWED_HEADERS:Authorization,Content-Type,Accept,Origin,User-Agent,Cache-Control,Pragma}
      allow-credentials: ${ALLOW_CREDENTIALS:true}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}
    default-folder: ${CLOUDINARY_FOLDER:shirtshop}

  payment:
    promptpay:
      target: ${PROMPTPAY_TARGET:0952544014}
      expire-minutes: ${PROMPTPAY_EXPIRE_MINUTES:10}

ml:
  gradio:
    base-url: ${ML_BASE_URL:}
    endpoint: ${ML_ENDPOINT:/api/tryon}     # ให้ใช้ path นี้ให้ตรงกับ ML จริง
    mode: ${ML_MODE:json}
    description: ${ML_DESCRIPTION:Short Sleeve Round Neck T-shirts}
    is-checked: ${ML_IS_CHECKED:true}
    is-checked-crop: ${ML_IS_CHECKED_CROP:false}
    denoise-steps: ${ML_DENOISE_STEPS:30}
    seed: ${ML_SEED:42}

# ---------- โพรไฟล์ DEV (เลือกใช้เมื่อรันโลคัล) ----------
# ใช้ Mailpit/MailHog เพื่อดูอีเมลในเบราว์เซอร์ ไม่ส่งออกจริง
---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: ${DEV_SMTP_HOST:localhost}
    port: ${DEV_SMTP_PORT:1025}
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# เปิด CORS ให้โลคัลได้สะดวก
app:
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS_DEV:http://localhost:3000,http://localhost:5173}
