server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, profile, email]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
          facebook:
            client-id: ${FB_CLIENT_ID}
            client-secret: ${FB_CLIENT_SECRET}
            scope: [email, public_profile]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui

app:
  jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000
  security:
    cors:
      allowed-origins:
        - ${FRONTEND_ORIGIN:http://localhost:3000}
        - http://localhost:5173
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    default-folder: ${CLOUDINARY_FOLDER}
  oauth2:
    redirect-success: ${OAUTH2_REDIRECT_SUCCESS:http://localhost:3000/oauth2/success}
    redirect-failure: ${OAUTH2_REDIRECT_FAILURE:http://localhost:3000/login?social=failed}
